# ESPN Fantasy Basketball League Configuration

league:
  id: "40204"
  season: 2025
  platform: "ESPN"

# Fantasy scoring categories (11 total)
categories:
  - name: "FG%"
    type: "percentage"
    better: "higher"
  - name: "FT%"
    type: "percentage"
    better: "higher"
  - name: "3P%"
    type: "percentage"
    better: "higher"
  - name: "3PM"
    type: "counting"
    better: "higher"
  - name: "PTS"
    type: "counting"
    better: "higher"
  - name: "REB"
    type: "counting"
    better: "higher"
  - name: "AST"
    type: "counting"
    better: "higher"
  - name: "STL"
    type: "counting"
    better: "higher"
  - name: "BLK"
    type: "counting"
    better: "higher"
  - name: "TO"
    type: "counting"
    better: "lower"
  - name: "DD"
    type: "counting"
    better: "higher"
    description: "Double-Doubles"

# Roster settings
roster:
  slots:
    PG: 1
    SG: 1
    SF: 1
    PF: 1
    C: 1
    G: 1  # Guard (PG/SG)
    F: 1  # Forward (SF/PF)
    UTIL: 3  # Any position
    BENCH: 3
  total_players: 13

# Matchup schedule
schedule:
  weeks: 23
  start_date: "2024-10-22"
  end_date: "2025-03-30"
  playoffs_start_week: 21

# Week mapping (from original code)
week_dates:
  1: ["2024-10-22", "2024-10-27"]
  2: ["2024-10-28", "2024-11-03"]
  3: ["2024-11-04", "2024-11-10"]
  4: ["2024-11-11", "2024-11-17"]
  5: ["2024-11-18", "2024-11-24"]
  6: ["2024-11-25", "2024-12-01"]
  7: ["2024-12-02", "2024-12-08"]
  8: ["2024-12-09", "2024-12-15"]
  9: ["2024-12-16", "2024-12-22"]
  10: ["2024-12-23", "2024-12-29"]
  11: ["2024-12-30", "2025-01-05"]
  12: ["2025-01-06", "2025-01-12"]
  13: ["2025-01-13", "2025-01-19"]
  14: ["2025-01-20", "2025-01-26"]
  15: ["2025-01-27", "2025-02-02"]
  16: ["2025-02-03", "2025-02-09"]
  17: ["2025-02-10", "2025-02-16"]
  18: ["2025-02-17", "2025-02-23"]
  19: ["2025-02-24", "2025-03-02"]
  20: ["2025-03-03", "2025-03-09"]
  21: ["2025-03-10", "2025-03-16"]  # Playoffs Round 1
  22: ["2025-03-17", "2025-03-23"]  # Playoffs Round 2
  23: ["2025-03-24", "2025-03-30"]  # Championship

# Data sources
data_sources:
  espn_api:
    base_url: "https://fantasy.espn.com/apis/v3/games/fba"
    endpoints:
      league: "/seasons/{season}/segments/0/leagues/{league_id}"
      players: "/seasons/{season}/segments/0/leagues/{league_id}/players"
  nba_api:
    use_local_cache: true
    rate_limit_ms: 1000